import '../sass/style.scss';
import { Hind, Lora } from 'next/font/google';

import Footer from '@/components/Footer';

/*****************
 * metadata
 */
export const metadata = {
  title: 'Stromdaten-Viewer',
  description: 'Generated by create next app',
}
/*****************
 * Fonts
 */
const hindStyles = Hind({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
  style: 'normal',
  display: 'swap',
  variable: '--font-hind',
})

const loraStyles = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  style: 'normal',
  display: 'swap',
  variable: '--font-lora',
})
/*************************
 * Root Layout
 *
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className={`${hindStyles.variable} ${loraStyles.variable}`}
    >
      <body >
        <div className="site-wrapper" >
          <div className="site-content">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
